name: Vercel Production Backend Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.BACKEND_PRD_VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
    paths:
      - backend/**

defaults:
  run:
    working-directory: backend
    
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }} 
      - name: Clean modules
        run: npm run clean
      - name: Create .env
        run: touch .env
      - name: Fill envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_PORT: ${{ secrets.BACKEND_PRD_PORT }}
          envkey_SECRET_JWT_KEY: ${{ secrets.BACKEND_PRD_SECRET_JWT_KEY }}
          envkey_DB_URI: ${{ secrets.BACKEND_PRD_DB_URI }}
          envkey_EMAIL_USER: ${{ secrets.BACKEND_PRD_EMAIL_USER }}
          envkey_MAILERSEND_API_KEY: ${{ secrets.BACKEND_PRD_MAILERSEND_API_KEY }}
          file_name: .env
          some_other_variable: foobar
          directory: backend
          fail_on_empty: false
          sort_keys: false
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }} 
      - name: Deploy Project Artifacts to Vercel
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }} 
